name: "Post dooray task"
description: "Post task to specific dooray project."

inputs:
  project:
    description: 'Project ID of dooray'
    required: true
  token:
    description: 'Authorization Token for using dooray API'
    required: true
  subject:
    description: 'Subject of release'
    required: true
  content:
    description: 'Content of release'
    required: false

runs:
  using: composite
  steps:
    - name: Run
      run: go run post_dooray_task.go
      shell: bash
