name: "Post dooray task"
description: "Post task to specific dooray project."

runs:
  using: composite
  steps:       
    - uses: actions/checkout@v3
      with:
        repository: wagstyle/dooray-action.post-task
        ref: v0.1.13

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run
      run: go run post_dooray_task.go
      shell: bash
