name: "Post dooray task"
description: "Post task to specific dooray project."

runs:
  using: composite
  steps:
    - name: See directory
      run: |
        ls -la
        
    - name: Run
      run: go run post_dooray_task.go
      shell: bash
